# Generated by Django 4.2.13 on 2024-05-16 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('tc', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Two Wheeler', 'Two Wheeler'), ('Four Wheeler', 'Four Wheeler'), ('Commercial Vehicle', 'Commercial Vehicle')], max_length=50)),
                ('vehicle_number', models.CharField(max_length=15)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=15)),
                ('registration_date', models.DateField()),
                ('seats', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(default='MSPOL', max_length=20)),
                ('description', models.TextField(default='This Insurance Policy will provide financial protection against damage or loss to your vehicle due to accidents, theft, or natural disasters, as well as covers the liability claims arising from third-party injuries or property damage.', max_length=1000)),
                ('base_premium', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('personal_accident_premium', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('passenger_cover_premium', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('breakdown_assistance_premium', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_premium', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('insured_declared_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('policy_status', models.CharField(choices=[('Active', 'Active'), ('Pay to Activate Your Policy', 'Pay to Activate Your Policy'), ('Pending For Approval', 'Pending For Approval'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending For Approval', max_length=50)),
                ('payment_status', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, default=None, null=True)),
                ('expires_on', models.DateField(blank=True, default=None, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MotorInsuranceCompany.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Undisclosed', 'Undisclosed')], max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MotorInsuranceCompany.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_claim', models.DateField()),
                ('description_of_incident', models.TextField()),
                ('reason_for_claim', models.CharField(max_length=50)),
                ('claim_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Settled', 'Settled'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('claimant_bank_name', models.CharField(max_length=80)),
                ('claimant_account_number', models.CharField(max_length=20)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MotorInsuranceCompany.policy')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MotorInsuranceCompany.vehicle')),
            ],
        ),
    ]
